[tool.pylint.messages_control]
disable = [
    "missing-module-docstring",
    "missing-class-docstring",
    "missing-function-docstring",
    "too-few-public-methods",

]

[tool.black]
line-length = 79
target-version = ["py310"] 

[tool.isort]
profile = "black"          # keep compatible with Black
line_length = 79           # match PEP 8 (or 88 if you prefer Black’s default)
force_sort_within_sections = true
length_sort = true         # <-- sort by length instead of alphabetically


