{
 "title": "Monitoring",
 "time": { "from": "2022-02-01T00:00:00.000Z", "to": "2022-03-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Number of duplicate columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_dup_cols, timestamp from dummy_metrics"
    }
   ]
  },
  {
   "title": "Number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_cols, timestamp from dummy_metrics"
    },
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "description": "It describes the drift in the prediction between the reference dataset and the current dataset",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, timestamp FROM \"dummy_metrics\""
    }
   ]
  }
 ]
}