source_stream_name = "ride-events"
destination_stream_name = "ride-predictions"
bucket_name = "stg-mlflow-models-priyan"
ecr_repo_name = "stg_stream_model_duration"
lambda_function_local_path = "../code/lambda_function.py"
docker_image_local_path = "../code/Dockerfile"
lambda_function_name = "stg_prediction_lambda"